<?php
//Proposal Class
//Used for loading proposals 
class Proposal {
    private $ID;
    private $Instructor; 
    private $InstructorEmail;
    private $CoInstructor;
    private $CoInstructorEmail;
    private $Sponsor;
    private $approvingDean; // This will be an integer which is tied to an approving dean from a different table
    private $Disciplines; // this is going to be an array of discipline ID's
    private $Title;
    private $Problem;
    private $Objective;
    private $Approach;
    private $Semesters; //array this will be stored as semester ID's in the form of YEAR+CODE example 2013FAL, 2014SPR, 2014SUM, these will be autogenerated
    private $Days; //array of days in form. 0=SUN 1=MON 2=TUES 3=WED 4=THURS 5=FRI 6=SAT so array{2,4} would be TUESDAY + THURSDAY
    private $TimeStart;
    private $TimeEnd;
    private $CourseNumber; // This will be 0 by default and when approved will be assigned an IPRO number IPRO 397-###
    private $OwnerID;
    private $dbconn;
    function __construct($proposalID){
        //This class is used to load and store proposal objects to and from the database
        $this->dbconn = new Database();
        $this->dbconn = $this->dbconn->getConnection();
        
        
    }
    static function generateDisciplinesCheckboxes($checkedArray){
        //This function will generate checkboxes for the disciplines in the database.
        //First we must pull all of the disciplines from the database
        $sql = "SELECT * FROM disciplines";
        $result = $this->dbconn->query($sql);
        $discipleArray = array();
        while($rows = $result->fetch_assoc()){
            $discipleArray[$rows['id']] = $rows['disciplineName'];
        }
        //Next we generate checkBoxes
        if($checkedArray == 0){
            $checkedArray = array(0);
        }
        //Next we generate the checkboxes
        $output = '';
        for($i=1;$i < count($discipleArray);$i++){
            if(in_array($i, $checkedArray)){
                $checked = 'checked="checked"';
            }
            $output .= '<input type="checkbox" '.$checked.' name="disc-'.$i.'">';
        }
        return $output;
    }
    
    
}

?>
